# Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/Texter
branches:
  - master
  - dev/3.5
projects:
  Texter:
    path: ""
    icon: "/assets/Logo.png"
    libs:
      - src: fuyutsuki/AccessorsTrait/accessors-trait
        version: ^0.4.0
        branch: dev/0.4-php7.3
      - src: fuyutsuki/libdesign-pattern/libdesign-pattern
        version: ^0.1.0
        branch: dev/0.1-php7.3
      - src: jojoe77777/FormAPI/libFormAPI
        version: 1.3.0
